### ISSUE TITLE
Questionário Criação

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#15]
### Descrição:
Aplicação de um questionário para validar o escopo e requisitos do projeto

### Critérios de Aceitação
- [x] Questionário que aborde uma totalidade do projeto.
- [x] Seja validado pelo time primeiramente

### Tarefas
- [x] Abrir a criação de um questionário no google
- [x] Compartilhar com a equipe
- [x] Modularizar para usuário que vão o sistema e que também não vão usar
- [x] Disponibilizar o questionário para futuros testadores do sistema

**Comment by RomeuCarvalhoAntunes** [comment]
Vou criar o questionário para avaliar e priorizar as features do projeto, gostaria de mais uma pessoa para parear na elaboração do mesmo, pensando na elaboração durante o final de semana ou semana que vem....

**Comment by RomeuCarvalhoAntunes** [comment]
@vitorfhc favor postar o link para que os outros membros do projeto possam avaliar o questionário antes de soltarmos para as respostas ...

**Comment by RomeuCarvalhoAntunes** [comment]
Para os interessados, aqui está o link para edição do questionário ![link](https://docs.google.com/forms/d/19k6uNB9DiTWdNwHCafVU-8HsxxGI3gKgRrZGt4wwuSM/edit)

**Comment by RomeuCarvalhoAntunes** [comment]
Realizei alguns incrementos no questionário estou no aguardo da revisão dos membros para poder divulgar.

**Comment by KahCosta** [comment]
@RomeuCarvalhoAntunes  acho que o questionário está ok e pronto para ser divulgado!

**Comment by RomeuCarvalhoAntunes** [comment]
Com a validação do questionário pelo time, realizei a divulgação, este ficará aberto por uma semana. Issue fechada, visto que o tratamento dos resultados do questionário será realizado em outra Issue.
