### ISSUE TITLE
Coleta dos dados do questionário e documentação

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#16]
### Descrição:
Após a aplicação do questionário coletar os dados e documentar

### Critérios de Aceitação
- [ ] Questionário analisado
- [ ] Questionário documentado
- [ ] Dados coletados na wiki 

### Tarefas
- [ ] Abrir o questionário
- [ ] Analisar gráficos e dados coletados
- [ ] Gerar um relatório baseado na analise dos dados
- [ ] Passar dados para wiki

**Comment by RomeuCarvalhoAntunes** [comment]
Vou criar o questionário para avaliar e priorizar as features do projeto, gostaria de mais uma pessoa para parear na elaboração do mesmo, pensando na elaboração durante o final de semana ou semana que vem....

**Comment by RomeuCarvalhoAntunes** [comment]
Documento revisado e aprovado, o questionário comprova a necessidade do projeto e que o grupo está no caminho certo. Issue fechada !
