### ISSUE TITLE
Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#17]
### Descrição:
Desenvolvimento de protótipo de alta fidelidade para melhor diagramar o fluxo da aplicação baseado no protótipo de baixa fidelidade

### Critérios de Aceitação
- [ ] Protótipo com maior abordagem possível sobre o projeto 
- [ ] Abordar telas que não foram descritas no protótipo de baixa fidelidade
- [ ] Validação por pelo menos 3 integrantes do grupo
- [ ] Protótipo compartilhado na issue

### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [ ] Utilizar da ferramenta quant-ux para produzir
- [ ] Melhorar o fluxo da aplicação
- [ ] Compartilhar na wiki do repositório

**Comment by victorcmoura** [comment]
Ideia dropada para evitar retrabalho. Tudo será feito no front do django
