### ISSUE TITLE
Criação/Atualização das politicas de commit, branch, pull request

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#2]
- [x] commit
- [x] branch
- [x] pull request
- [x] issue

**Comment by RomeuCarvalhoAntunes** [comment]
Issue Finalizada !

**Comment by gabrielziegler3** [comment]
Reformulada política de commits para o uso do modo imperativo, seguindo como referecial este [post](https://chris.beams.io/posts/git-commit/).

**Comment by arthurbdiniz** [comment]
Como essa refatoração teve uma demanda em cima da hora vou colocar para próxima milestone

**Comment by RomeuCarvalhoAntunes** [comment]
Nova política validada. Issue Fechada !
