### ISSUE TITLE
Decisão do nome do projeto

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#23]
### Descrição:
Decisão do nome do projeto

### Critérios de Aceitação
- [ ] Definição do nome do projeto.

### Tarefas
- [ ] Cada integrante do grupo comentar um nome para o projeto

**Comment by RomeuCarvalhoAntunes** [comment]
Lumos

**Comment by KahCosta** [comment]
Portifólio Fga

**Comment by vitorfhc** [comment]
Doorfólio

**Comment by wdresende** [comment]
CaFGA --- Se ler Café FGA, Café por ser um símbolo do desenvolvedor. Sei que não fica muito bom a sonoridade, mas é uma sugestão

**Comment by arthurbdiniz** [comment]
Spatium

**Comment by RomeuCarvalhoAntunes** [comment]
O nome do projeto foi decidido hoje em sala, por meio de uma argumentação que será esboçada em outra issue...

**Comment by RomeuCarvalhoAntunes** [comment]
Nome definido: GitPub

Issue Fechada !
