### ISSUE TITLE
Criar logo 

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#24]
### Descrição:
Baseado no tema criar uma brand para o projeto

### Critérios de Aceitação
- [x] Logo em vários formatos diferentes

**Comment by victorcmoura** [comment]
Opção 1:
![image](https://user-images.githubusercontent.com/26290053/44741329-16ac1d80-aad3-11e8-8176-a80beabc2658.png)
Opção 2:
![image](https://user-images.githubusercontent.com/26290053/44741342-21ff4900-aad3-11e8-9797-f0e3c065c444.png)

**Comment by victorcmoura** [comment]
Opção 3:
![image](https://user-images.githubusercontent.com/26290053/44758448-d2d50a80-ab0a-11e8-985d-7e5fa753b252.png)

**Comment by arthurbdiniz** [comment]
Curti a opção 1 e 3, tenta fazer mais 1 opção colocando a cor do texto cinza da cor do canudo pra ver como fica. Acho que ficaria massa.

**Comment by victorcmoura** [comment]
Opção 4:
![image](https://user-images.githubusercontent.com/26290053/44795036-203f8f00-ab80-11e8-9211-75fe08e46c31.png)

**Comment by victorcmoura** [comment]
O que achou, @arthurbdiniz?

**Comment by arthurbdiniz** [comment]
As logos já estão criadas, acredito que agora é questão de colorização da fonte, então estarei fechando essa issue.
