### ISSUE TITLE
Plano de Elicitação de Requisitos

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#28]
### Descrição:
Com intuito de definir todo o escopo e contexto do projeto é necessário criar um plano de elicitação de requisitos.

### Critérios de Aceitação
- [x] Plano criado 

### Tarefas
- [x] Avaliar o que vai ser usado para o levantamento dos requisitos

**Comment by arthurbdiniz** [comment]
Versão iniciar do plano de elicitação de requisitos já esta na [wiki](https://github.com/Desenho2018-2/Main/wiki/Plano-Elicitacao-Requisitos), gostaria uma revisão de alguem do time

**Comment by RomeuCarvalhoAntunes** [comment]
Versão inicial de acordo com o planejado, documento revisado, caso seja necessário durante o projeto esse plano poderá sofrer alterações. Issue Fechada !
