### ISSUE TITLE
Técnica de Priorização  MoSCoW

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#31]
### Descrição:
Após o levantamento dos requisitos e a coleta dos dados do brainstorm e questionário, utilizar de técnicas de priorização para definir o escopo do projeto.

### Critérios de Aceitação
- [ ] MoSCoW.
- [ ] Documento Versionado

### Tarefas
- [ ] Analisar brainstorm
- [ ] Analisar coleta de dados do questionário
- [ ] Produzir o MoSCoW priorizando as funcionalidades chaves

**Comment by RomeuCarvalhoAntunes** [comment]
Revisado, tudo ok. Issue Fechada !
