### ISSUE TITLE
Cenários V1

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#33]
### Descrição:
Utilizado para entender o cenário da aplicação junto com os léxicos 

### Critérios de Aceitação
- [ ] Estrutura básica dos cenários
- [ ] Documentos revisado pelo time

### Tarefas
- [ ] Ver os documentos já produzidos 
- [ ] Avaliar e criar os cenários dentro do contexto do projeto

**Comment by RomeuCarvalhoAntunes** [comment]
Criar apenas um documento para todos os cenários.

**Comment by RomeuCarvalhoAntunes** [comment]
Criação do documento e dos cenários:   Acessar o GitPub pelo navegador; Cadastrar-se na plataforma GitPub

**Comment by arthurbdiniz** [comment]
A matriz de rastreabilidade vai contemplar os cenários
