### ISSUE TITLE
MoSCoW para definição dos documentos

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#36]
### Critérios de Aceitação
- [ ] MoSCoW com a priorização dos documentos utilizados no projeto.
- [ ] Revisão do time

### Tarefas
- [ ] Estudar documentos de requisitos
- [ ] Priorizar utilizando MoSCoW

**Comment by gabrielziegler3** [comment]
Iniciado na [wiki](https://github.com/Desenho2018-2/GitPub/wiki/Prioriza%C3%A7%C3%A3o-Documentos)

**Comment by victorcmoura** [comment]
Inseri no documento algumas priorizações. Uma delas eu não inseri (storytelling) pois não tenho o feedback do grupo em relação a ela.

**Comment by arthurbdiniz** [comment]
Quem está responsável pelo storytelling é a @KahCosta

**Comment by gabrielziegler3** [comment]
priorizacao feita, deem uma olhada, pfvr.

**Comment by RomeuCarvalhoAntunes** [comment]
Documento revisado e aprovado !
