### ISSUE TITLE
Argumentação definição do nome

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#40]
### Critérios de Aceitação
- [x] Argumentação sobre a definição do nome
- [ ] Argumentação revisada pelo time

### Tarefas
- [x] Relembrar conversa em sala
- [x] Desenvolver argumentação

**Comment by joao4018** [comment]
Argumentação postada na [wiki](https://github.com/Desenho2018-2/GitPub/wiki/Argumenta%C3%A7%C3%A3o#nome), falta apenas revisão de algum membro.

**Comment by arthurbdiniz** [comment]
![image](https://user-images.githubusercontent.com/18387694/44913160-e945b680-ad02-11e8-805e-8c084b19abb6.png)

Achei apenas um erro de português para ser corrigido.

**Comment by arthurbdiniz** [comment]
Fiz  correção e estou fechando a issue
