### ISSUE TITLE
Automação das Dailies

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#43]
### Descrição:
Evitar o overhead de ficar criando issues das dailys.

### Critérios de Aceitação
- [x] Bot criando e fechando issues de dailys 

### Tarefas
- [x] Estudar aplicação do bot
- [x] Criar bot
- [ ] Aplicar ao projeto

**Comment by victorcmoura** [comment]
Até agora, consegui criar um container docker que roda cronjobs. Falta criar o script Python para abrir e fechar a issue.

**Comment by arthurbdiniz** [comment]
Seria interessante utilizar o token da API de uma conta externa para as issues não ficarem no seu nome, tipo Scrum Bot

**Comment by arthurbdiniz** [comment]
Se puder subir os scripts criados em um repo dentro da organização para eu poder ajudar e melhorar o bot...

**Comment by arthurbdiniz** [comment]
Automação já foi testada e implementada, fechando issue
