### ISSUE TITLE
Criar matriz de rastreabilidade forward-from

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [Desenho2018-2/GitPub#46]
# Criar matriz de rastreabilidade forward-from

### Descrição:
Criação matriz de rastreabilidade forward-from, para auxiliar no desenvolvimento e acompanhamento do projeto, com a rastreabilidade dos requisitos.

### Critérios de Aceitação

- [ ] Documento por 3 membros do grupo

### Tarefas

- [ ] Criar documento para matriz
- [ ] Realizar o link da página com o menu lateral da wiki
- [ ] Popular a matriz com as funcionalidades já existentes

**Comment by victorcmoura** [comment]
Primeira versão concluída. Basta remover os gaps (criando os itens faltantes) e atualizar a tabela:
[Matrizes de rastreabilidade](https://github.com/Desenho2018-2/GitPub/blob/master/docs/Matrizes-de-rastreabilidade.md)
