### ISSUE TITLE
NFR Framework

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#53]
### Descrição:
 É um framework para modelagem de metas. A análise começa com softgoals que representam o NFR no qual as partes interessadas concordam. Softgoals são objetivos difíceis de expressar, mas tendem a ser qualidades globais de um sistema de software.

### Critérios de Aceitação
- [x] Documento Criado
- [x] Documento Revisado

### Tarefas
- [x] Analisar aplicação do NFR
- [x] Modelar as metas do projeto

**Comment by victorcmoura** [comment]
Feito: 8aaabb74c415da00f1d98aac6dc8e546e9c56bef
