### ISSUE TITLE
Verificação 

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#54]
### Descrição:
Durante e após a produção do software verificar para ter a assertividade de que todos os requisitos planejados foram feitos ou estão feitos da forma correta.

### Critérios de Aceitação
- [ ] Verificação aplicada para todo o projeto
- [ ] Todas as funcionalidades planejadas dentro do software

### Tarefas
- [ ] Analisar o software
- [ ] Verificar os requisitos levantados com as funcionalidades desenvolvidas

**Comment by RomeuCarvalhoAntunes** [comment]
Issue com trabalho duplicado, o processo de verificação será realizado pelo Checklist neste [Link](https://github.com/Desenho2018-2/GitPub/issues/55)
