### ISSUE TITLE
Melhorar a página inicial da wiki

### ISSUE THREAD

**Issue by gabrielziegler3** [Desenho2018-2/GitPub#56]
### Tarefas
Seção para tarefas de Issues mais complexas. As tarefas devem garantir o perfeito funcionamento da Issue.
- [x] Adicionar descrição da wiki do projeto
- [x] Adicionar tabela com desenvolvedores

**Comment by gabrielziegler3** [comment]
Adicionada nova [homepage](https://github.com/Desenho2018-2/GitPub/wiki)

**Comment by RomeuCarvalhoAntunes** [comment]
Revisado e aprovado. Issue fechada
