### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by joao4018** [Desenho2018-2/GitPub#73]
### Descrição:
Documento que descreve o funcionamento geral do software, detalhando cada passo seguido pelos desenvolvedores e caracterizando o mesmo, buscando reduzir ao máximo os riscos do produto, protegendo os desenvolvedores e os clientes.

### Critérios de Aceitação
Critérios de aceitação para a Issue ser aceita.
- [ ] Documento final na wiki.
- [ ] Revisado por algum membro.

**Comment by victorcmoura** [comment]
Não enxergamos a necessidade real do documento de visão, tendo em vista que o foco da disciplina é desenho e arquitetura
