### ISSUE TITLE
Diagrama da metodologia do time

### ISSUE THREAD

**Issue by RomeuCarvalhoAntunes** [Desenho2018-2/GitPub#74]
# Diagrama da metodologia do time
---
### Descrição:
Diagrama criado com o intuito de facilitar a visualização das práticas e das rotinas do time durante o projeto

### Critérios de Aceitação
- [x] Revisão por outro membro.
- [x] Diagrama criado

### Tarefas
- [x] Criar diagrama

**Comment by RomeuCarvalhoAntunes** [comment]
Diagrama que está aguardando a revisão. 

![processo](https://user-images.githubusercontent.com/18054053/45429190-2a31b980-b679-11e8-9f82-3504d3c9d4dc.png)

**Comment by victorcmoura** [comment]
@RomeuCarvalhoAntunes, acredito que está tudo certinho. Como verifiquei que o [doc](https://github.com/Desenho2018-2/GitPub/wiki/Metodologia) está atualizado, a issue está sendo fechada
