### ISSUE TITLE
Backward-from

### ISSUE THREAD

**Issue by arthurbdiniz** [Desenho2018-2/GitPub#81]
### Descrição:
Saindo do requisito para o documento

### Critérios de Aceitação
- [x] Documento linkado na wiki.
- [ ] Documento revisado por pelo menos um integrante do projeto 
 
### Tarefas
- [x] Fazer o rastreio dos requisitos do requisito para o documento
- [x] Documentar em uma matriz de rastreabilidade
- [x] Criar e atualizar histórico de versionamento

**Comment by victorcmoura** [comment]
Documento disponível em: https://github.com/Desenho2018-2/GitPub/blob/master/docs/Matrizes-de-rastreabilidade.md
