### ISSUE TITLE
Completar gaps das matrizes de rastreabilidade

### ISSUE THREAD

**Issue by victorcmoura** [Desenho2018-2/GitPub#82]
### Descrição:
As matrizes de rastreabilidade possuem gaps (faltam cenários, casos de uso, features...) que precisam ser eliminados.

### Critérios de Aceitação
- [ ] Matrizes de rastreabilidade sem gaps

### Tarefas
- [ ] Criar cenários para completar os gaps das matrizes

**Comment by victorcmoura** [comment]
Peço para que se atentem à edição feita na descrição da issue:

![image](https://user-images.githubusercontent.com/26290053/45496382-b01e3500-b74b-11e8-8a78-6176c06a3552.png)

Não são faltantes apenas os cenários. Também é necessário criar features e casos de uso.

**Comment by wdresende** [comment]
Fiquei com dúvida na parte de implementação, não colocamos nada por enquanto? já que não temos a implementação

**Comment by victorcmoura** [comment]
Gaps preenchidos. Fechando issue
