### ISSUE TITLE
Cadastrar o backlog em formato de issue

### ISSUE THREAD

**Issue by victorcmoura** [Desenho2018-2/GitPub#90]
### Descrição:
Deve-se, baseando-se no Backlog do Produto, criar issues de desenvolvimento da aplicação. 

### Critérios de Aceitação
- [x] Issues criadas com base no backlog do produto

### Tarefas
- [x] Construir o Roadmap do Produto
- [x] Cadastrar issues baseadas no roadmap do produto

**Comment by arthurbdiniz** [comment]
Acredito que todo backlog já esta cadastrado
